name: "【Docker】Ruby on Rails CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  run-htmlbeautifier:
    name: Run htmlbeautifier
    runs-on: ubuntu-latest
    steps:
      - name: checkout pushed commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create .env file
        run: |
          echo "BASIC_AUTH_USER=${{ secrets.BASIC_AUTH_USER }}" >> .env
          echo "BASIC_AUTH_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }}" >> .env
      - name: run htmlbeautifier on docker-compose
        run: |
          docker compose build
          docker compose run --rm web bin/setup
          docker compose run --rm web bin/htmlbeautifier
          git diff --exit-code
